const paths={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',people:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18m-13 4h3m3 0h3"/>',wallet:'<rect x="3" y="6" width="18" height="15" rx="2"/><path d="M3 7V5a2 2 0 0 1 2-2h12v3m4 7h-6v4h6"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>'};
paths.sun='<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>';
const icon=(name)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.people}</svg>`;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const employees=[{name:'Aditya Pratama',email:'aditya@temancipta.demo',role:'Senior Product Designer',dept:'Design',status:'Hadir',time:'08:48',salary:12000000},{name:'Nadia Putri',email:'nadia@temancipta.demo',role:'Frontend Developer',dept:'Engineering',status:'Hadir',time:'08:52',salary:11000000},{name:'Rizky Ramadhan',email:'rizky@temancipta.demo',role:'Digital Marketing Specialist',dept:'Marketing',status:'Terlambat',time:'09:12',salary:8000000},{name:'Sarah Wijaya',email:'sarah@temancipta.demo',role:'HR Business Partner',dept:'People & Operations',status:'Hadir',time:'08:35',salary:9500000},{name:'Fajar Maulana',email:'fajar@temancipta.demo',role:'Backend Developer',dept:'Engineering',status:'Cuti',time:'—',salary:11500000},{name:'Dinda Amelia',email:'dinda@temancipta.demo',role:'Finance Officer',dept:'Finance',status:'Hadir',time:'08:50',salary:8500000},{name:'Bima Saputra',email:'bima@temancipta.demo',role:'UI Designer',dept:'Design',status:'Hadir',time:'08:40',salary:8000000},{name:'Alya Maharani',email:'alya@temancipta.demo',role:'Content Strategist',dept:'Marketing',status:'Hadir',time:'08:55',salary:7500000}];
const leaves=[{name:'Nadia Putri',dept:'Engineering',type:'Cuti tahunan',date:'10–11 Sep 2026',days:2,status:'Menunggu',reason:'Keperluan keluarga'},{name:'Aditya Pratama',dept:'Design',type:'Cuti tahunan',date:'14 Sep 2026',days:1,status:'Menunggu',reason:'Keperluan pribadi'},{name:'Sarah Wijaya',dept:'People & Operations',type:'Izin pribadi',date:'16 Sep 2026',days:1,status:'Menunggu',reason:'Mengurus dokumen'}];
const menus=[['dashboard','Dashboard','dashboard'],['karyawan','Karyawan','people'],['absensi','Absensi','clock'],['cuti','Cuti & izin','calendar'],['payroll','Payroll','wallet']];let current='dashboard';let query='';let dept='Semua departemen';let period='week';
const initials=n=>n.split(' ').slice(0,2).map(x=>x[0]).join('');
const colors=['#e9edde','#eee5de','#e5ebf3','#f1e5e8','#e5efeb','#efe9f4'];
const avatar=(n,i=0)=>`<span class="avatar" style="background:${colors[i%colors.length]}">${esc(initials(n))}</span>`;
const badge=s=>`<span class="badge ${['Hadir','Disetujui','Aktif'].includes(s)?'green':['Terlambat','Menunggu'].includes(s)?'warning':'blue'}">${esc(s)}</span>`;
const money=n=>'Rp'+new Intl.NumberFormat('id-ID').format(n);
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3500)}
function nav(){document.querySelector('#nav').innerHTML=menus.map(([id,title,i])=>`<a href="#${id}" class="${current===id?'active':''}" ${current===id?'aria-current="page"':''}><span class="nav-icon">${icon(i)}</span>${title}${id==='cuti'?`<span class="count">${leaves.filter(l=>l.status==='Menunggu').length}</span>`:''}</a>`).join('');document.querySelector('#crumb').textContent=menus.find(m=>m[0]===current)[1]}
function heading(title,sub,actions=''){return `<div class="page-heading"><div><div class="eyebrow">TEMANCIPTA / PEOPLE & CULTURE</div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="heading-actions">${actions}</div></div>`}
const addButton=()=>`<button class="button primary" data-action="add">${icon('plus')}Tambah karyawan</button>`;
function stats(){const present=employees.filter(e=>e.status==='Hadir').length;const pending=leaves.filter(l=>l.status==='Menunggu').length;return `<div class="stats">${[["Total karyawan",employees.length,"orang","people","5 departemen","di perusahaan"],["Hadir hari ini",present,"orang","clock",`${Math.round(present/employees.length*100)}%`,"tingkat kehadiran"],["Cuti & izin",employees.filter(e=>e.status==='Cuti').length,"orang","calendar","Hari ini","izin disetujui"],["Menunggu persetujuan",pending,"pengajuan","wallet","Perlu ditinjau","cuti & izin"]].map(([title,value,unit,i,note,detail])=>`<div class="stat"><div class="stat-top">${title}<span class="stat-icon">${icon(i)}</span></div><div class="stat-value"><span data-counter="${value}">${value}</span><small>${unit}</small></div><div class="stat-note"><span class="pill-up">${note}</span>${detail}</div></div>`).join('')}</div>`}
function chart(){const values=period==='week'?[88,75,88,100,75]:[81,86,92,88];const labels=period==='week'?['Sen','Sel','Rab','Kam','Jum']:['Minggu 1','Minggu 2','Minggu 3','Minggu 4'];return `<section class="card"><div class="card-head"><div><h2>Statistik kehadiran</h2><span class="card-sub">Ringkasan kehadiran tim kamu</span></div><select id="period" aria-label="Periode grafik"><option value="week" ${period==='week'?'selected':''}>Minggu ini</option><option value="month" ${period==='month'?'selected':''}>Bulan ini</option></select></div><div class="chart-legend"><span><i class="legend-key"></i>Hadir</span><span><i class="legend-key light"></i>Cuti / tidak hadir</span></div><div class="chart"><div class="y-labels"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0%</span></div><div class="plot" role="img" aria-label="Contoh kehadiran ${values.map((v,i)=>labels[i]+': '+v+' persen').join(', ')}">${values.map((v,i)=>`<div class="bar-group" title="${labels[i]}: ${v}% hadir"><div class="bar" style="height:${v}%"></div><div class="bar light" style="height:${100-v}%"></div><span class="bar-label">${labels[i]}</span></div>`).join('')}</div></div><div class="chart-bottom"><span><strong>${Math.round(values.reduce((a,b)=>a+b,0)/values.length)}%</strong> rata-rata kehadiran · ilustrasi</span><a href="#absensi" class="text-link">Detail absensi ${icon('arrow')}</a></div></section>`}
function leaveItems(full=false){let list=full?leaves:leaves.filter(l=>l.status==='Menunggu').slice(0,3);return list.length?list.map(l=>`<div class="leave-item">${avatar(l.name,leaves.indexOf(l))}<div class="leave-info"><strong>${esc(l.name)}</strong><p>${esc(l.type)} · ${l.days} hari</p>${full?`<p>${esc(l.reason)} · ${esc(l.dept)}</p>`:''}<span class="badge">${l.date}</span>${full&&l.status==='Menunggu'?`<div class="approval-actions"><button class="button primary" data-decision="Disetujui" data-index="${leaves.indexOf(l)}">Setujui</button><button class="button" data-decision="Ditolak" data-index="${leaves.indexOf(l)}">Tolak</button></div>`:''}</div><div>${badge(l.status)}</div></div>`).join(''):'<div class="empty">Semua pengajuan sudah ditinjau.</div>'}
function searchTools(){return `<div class="toolbar"><div class="search">${icon('search')}<input id="search" placeholder="Cari karyawan..." aria-label="Cari karyawan" value="${esc(query)}"></div><select id="department" aria-label="Filter departemen">${['Semua departemen','Design','Engineering','Marketing','People & Operations','Finance'].map(d=>`<option ${dept===d?'selected':''}>${d}</option>`).join('')}</select></div>`}
function employeeTable(view='dashboard'){const list=employees.filter(e=>(e.name+' '+e.role+' '+e.email).toLowerCase().includes(query.toLowerCase())&&(dept==='Semua departemen'||e.dept===dept));const visible=view==='dashboard'?list.slice(0,4):list;let headers=view==='payroll'?['Karyawan','Departemen','Gaji pokok','Tunjangan','Total bruto']:view==='absensi'?['Karyawan','Departemen','Jam masuk','Jam pulang','Status']:['Karyawan','Departemen','Posisi',view==='dashboard'?'Kehadiran':'Status'];return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${visible.map((e,i)=>`<tr><td><div class="person">${avatar(e.name,i)}<div><strong>${esc(e.name)}</strong><small>${esc(e.email)}</small></div></div></td><td>${esc(e.dept)}</td>${view==='payroll'?`<td>${e.salary?money(e.salary):'Belum diatur'}</td><td>${e.salary?money(500000):'—'}</td><td><b>${e.salary?money(e.salary+500000):'—'}</b></td>`:view==='absensi'?`<td>${e.time}</td><td>—</td><td>${badge(e.status)}</td>`:`<td>${esc(e.role)}</td><td>${badge(view==='dashboard'?e.status:'Aktif')}</td>`}</tr>`).join('')||`<tr><td colspan="5" class="empty">Tidak ada karyawan yang cocok.</td></tr>`}</tbody></table></div><div class="table-footer"><span>Menampilkan <b>${visible.length}</b> dari <b>${list.length}</b> karyawan</span>${view==='dashboard'?`<a class="text-link" href="#karyawan">Lihat semua ${icon('arrow')}</a>`:'<span>Data contoh · sesi ini</span>'}</div>`}
function tableCard(view){return `<section class="card table-card"><div class="card-head"><div><h2>${view==='dashboard'?'Daftar karyawan':view==='absensi'?'Kehadiran karyawan':view==='payroll'?'Rincian payroll':'Direktori karyawan'}</h2><span class="card-sub">${view==='absensi'?'Jumat, 4 September 2026 · Shift 09.00–18.00':view==='payroll'?'September 2026 · Simulasi gaji bruto':'Kenali orang-orang di balik tim kamu'}</span></div>${searchTools()}</div><div id="table-content">${employeeTable(view)}</div></section>`}
function render(){nav();let html='';if(current==='dashboard'){html=heading(`Selamat pagi, Admin <span class="greeting-icon">${icon("sun")}</span>`,'Ini yang sedang terjadi di tim kamu hari ini.',`<span class="button">${icon('calendar')}4 September 2026</span>${addButton()}`)+stats()+`<div class="dashboard-grid">${chart()}<section class="card"><div class="card-head"><div><h2>Pengajuan cuti & izin</h2><span class="card-sub">${leaves.filter(l=>l.status==='Menunggu').length} pengajuan menunggu persetujuan</span></div></div><div class="leave-list">${leaveItems()}</div><div class="card-foot"><a class="text-link" href="#cuti">Tinjau semua pengajuan ${icon('arrow')}</a></div></section></div>`+tableCard('dashboard')}else if(current==='karyawan'){html=heading('Karyawan','Satu tempat untuk mengenal dan mengelola tim kamu.',addButton())+tableCard('karyawan')}else if(current==='absensi'){html=heading('Absensi','Pantau kehadiran dan ketepatan waktu tim.',`<button class="button" data-action="export">${icon('download')}Ekspor absensi</button>`)+stats()+tableCard('absensi')}else if(current==='cuti'){html=heading('Cuti & izin','Tinjau kebutuhan waktu istirahat tim dengan mudah.')+`<div class="section-note">Persetujuan di halaman ini adalah simulasi. Status hanya berubah selama sesi ini dan tidak mengubah saldo cuti.</div><section class="card full-leaves"><div class="card-head"><div><h2>Semua pengajuan</h2><span class="card-sub">September 2026</span></div></div><div class="leave-list">${leaveItems(true)}</div></section>`}else{const total=employees.reduce((s,e)=>s+(e.salary?e.salary+500000:0),0);html=heading('Payroll','Ringkasan kompensasi tim untuk September 2026.')+`<div class="section-note">Simulasi payroll bruto: total gaji dan tunjangan <strong>${money(total)}</strong>. Belum termasuk pajak, BPJS, potongan, atau proses pembayaran.</div>`+tableCard('payroll')}document.querySelector('#main').innerHTML=html;document.title=`${menus.find(m=>m[0]===current)[1]} · TemanCipta`;animateSurface();}
function route(){const id=location.hash.slice(1);if(id==='main')return;current=menus.some(m=>m[0]===id)?id:'dashboard';query='';dept='Semua departemen';closeMenu();render()}
window.addEventListener('hashchange',route);document.querySelector('#menu').onclick=()=>{const open=document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#menu').setAttribute('aria-expanded',String(open));};
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='add')document.querySelector('#employee-dialog').showModal();if(action==='export'){const csv='\uFEFF'+[['Nama','Departemen','Jam masuk','Status'],...employees.map(x=>[x.name,x.dept,x.time,x.status])].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='absensi-demo-04-september-2026.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Laporan absensi berhasil diunduh.')}const decision=e.target.closest('[data-decision]');if(decision){leaves[Number(decision.dataset.index)].status=decision.dataset.decision;render();toast('Pengajuan '+decision.dataset.decision.toLowerCase()+'.')}if(e.target.closest('main')&&innerWidth<=650)closeMenu()});
document.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;document.querySelector('#table-content').innerHTML=employeeTable(current)}});document.addEventListener('change',e=>{if(e.target.id==='department'){dept=e.target.value;document.querySelector('#table-content').innerHTML=employeeTable(current)}if(e.target.id==='period'){period=e.target.value;render()}});
for(const id of ['close-dialog','cancel-dialog'])document.getElementById(id).onclick=()=>document.querySelector('#employee-dialog').close();
document.querySelector('#employee-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const record=Object.fromEntries(f);for(const key of ['name','email','role'])if(!record[key].trim()){toast('Lengkapi semua kolom terlebih dahulu.');return}if(employees.some(x=>x.email.toLowerCase()===record.email.trim().toLowerCase())){toast('Email kerja sudah digunakan.');return}employees.push({...record,name:record.name.trim(),email:record.email.trim(),role:record.role.trim(),status:'Belum absen',time:'—',salary:0});document.querySelector('#employee-dialog').close();e.target.reset();render();toast('Karyawan ditambahkan ke data demo sesi ini.')};
function closeMenu(){document.querySelector('#sidebar').classList.remove('open');document.querySelector('#menu').setAttribute('aria-expanded','false')}
route();

function animateSurface(){
  const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(reduced)return;
  const surfaces=document.querySelectorAll('#main .page-heading, #main .stat, #main .dashboard-grid > .card, #main > .table-card, #main > .full-leaves');
  surfaces.forEach((el,i)=>{el.style.setProperty('--enter-delay',`${Math.min(i*45,240)}ms`);el.classList.add('surface-enter');el.addEventListener('animationend',()=>el.classList.remove('surface-enter'),{once:true});});
  document.querySelectorAll('[data-counter]').forEach(el=>{const target=Number(el.dataset.counter);const start=performance.now();function tick(t){const p=Math.min((t-start)/650,1);el.textContent=String(Math.round(target*(1-Math.pow(1-p,3))));if(p<1&&el.isConnected)requestAnimationFrame(tick)}requestAnimationFrame(tick)});
}
document.addEventListener('pointermove',e=>{
  if(!window.matchMedia('(hover: hover) and (pointer: fine)').matches||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const card=e.target.closest('.stat');if(!card)return;
  const bounds=card.getBoundingClientRect();
  card.style.setProperty('--tilt-x',`${((e.clientY-bounds.top)/bounds.height-.5)*-5}deg`);
  card.style.setProperty('--tilt-y',`${((e.clientX-bounds.left)/bounds.width-.5)*6}deg`);
},{passive:true});
document.addEventListener('pointerout',e=>{const card=e.target.closest('.stat');if(card&&!card.contains(e.relatedTarget)){card.style.removeProperty('--tilt-x');card.style.removeProperty('--tilt-y')}},{passive:true});
document.addEventListener('click',e=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const button=e.target.closest('button.button');if(!button)return;const bounds=button.getBoundingClientRect();const ripple=document.createElement('span');ripple.className='click-ripple';ripple.setAttribute('aria-hidden','true');ripple.style.left=`${e.detail?e.clientX-bounds.left:bounds.width/2}px`;ripple.style.top=`${e.detail?e.clientY-bounds.top:bounds.height/2}px`;button.appendChild(ripple);ripple.addEventListener('animationend',()=>ripple.remove(),{once:true})});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
